//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactSectionSettings
    {
        public int ContactSectionId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string BadgeText { get; set; }
        public string Box1Icon { get; set; }
        public string Box1Title { get; set; }
        public string Box1Text { get; set; }
        public string Box1Url { get; set; }
        public string Box2Icon { get; set; }
        public string Box2Title { get; set; }
        public string Box2Text { get; set; }
        public string Box2Url { get; set; }
        public string Box3Icon { get; set; }
        public string Box3Title { get; set; }
        public string Box3Text { get; set; }
        public string Box3Url { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
