//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLogs
    {
        public int LoginLogId { get; set; }
        public string Username { get; set; }
        public bool IsSuccess { get; set; }
        public string IpAddress { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
