//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortfolioDbEntities : DbContext
    {
        public PortfolioDbEntities()
            : base("name=PortfolioDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Abouts> Abouts { get; set; }
        public DbSet<Admins> Admins { get; set; }
        public DbSet<Messages> Messages { get; set; }
        public DbSet<ProjectImages> ProjectImages { get; set; }
        public DbSet<Projects> Projects { get; set; }
        public DbSet<SiteSettings> SiteSettings { get; set; }
        public DbSet<Skills> Skills { get; set; }
        public DbSet<SocialMedias> SocialMedias { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<SkillCategories> SkillCategories { get; set; }
        public DbSet<ProjectSections> ProjectSections { get; set; }
        public DbSet<ContactSectionSettings> ContactSectionSettings { get; set; }
        public DbSet<LoginLogs> LoginLogs { get; set; }
    }
}
