//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public Projects()
        {
            this.ProjectImages = new HashSet<ProjectImages>();
            this.ProjectSections = new HashSet<ProjectSections>();
        }
    
        public int ProjectId { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string Technologies { get; set; }
        public string GithubUrl { get; set; }
        public string LiveDemoUrl { get; set; }
        public string ThumbnailUrl { get; set; }
        public bool IsFeatured { get; set; }
        public bool IsActive { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<ProjectImages> ProjectImages { get; set; }
        public virtual ICollection<ProjectSections> ProjectSections { get; set; }
    }
}
