//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSettings
    {
        public int SiteSettingId { get; set; }
        public string SiteTitle { get; set; }
        public string HeroTitle { get; set; }
        public string HeroSubtitle { get; set; }
        public string HeroBackgroundImageUrl { get; set; }
        public string FooterText { get; set; }
    }
}
