//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillCategories
    {
        public int SkillCategoryId { get; set; }
        public string CategoryName { get; set; }
        public string DisplayName { get; set; }
        public string ColorClass { get; set; }
        public string HexColor { get; set; }
        public bool IsActive { get; set; }
        public int DisplayOrder { get; set; }
    }
}
